Machine Learning / Predictive Analysis

In [ ]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Loading the data
data_base=pd.read_csv('base_insurance_data.csv')

In [ ]:
data_base.head()

,Claim_ID,Policy_ID,Claim_Date,Claim_Amount,Claim_Status,Claim_Type,Claim_Processing_Days,Customer_ID_x,Policy_Type,Policy_Start_Date,...,Occupation,City,Income,Age_Group,Transaction_ID,Customer_ID_y,Risk_Level,Previous_Claims,Customer_Risk_Score,Risk_Weight
0,CLM_000002,POL_000002,2025-09-24,424428,Rejected,Natural Disaster,8,CUST_000002,Motor,2025-08-22,...,Self-Employed,Pune,2771559.0,18-25,TXN_000002,CUST_000002,High,4.0,91.94,3.0
1,CLM_000004,POL_000004,2023-08-12,2082174,Approved,Accidental,40,CUST_000004,Home,2021-03-24,...,Salaried,Hyderabad,723630.0,18-25,TXN_000004,CUST_000004,Low,0.0,17.10,1.0
2,CLM_000005,POL_000005,2026-01-27,719296,Approved,Theft,6,CUST_000005,Motor,2024-10-27,...,Self-Employed,Pune,1891551.0,41-60,TXN_000005,CUST_000005,Low,1.0,29.90,1.0
3,CLM_000007,POL_000007,2023-08-23,93100,Pending,Natural Disaster,10,CUST_000007,Home,2022-10-31,...,Self-Employed,Bangalore,2437108.0,41-60,TXN_000007,CUST_000007,High,4.0,90.06,3.0
4,CLM_000012,POL_000012,2024-08-01,97597,Approved,Accidental,34,CUST_000012,Travel,2022-12-10,...,Salaried,Chennai,388224.0,18-25,TXN_000012,CUST_000012,Medium,1.0,38.63,2.0

In [ ]:
data_base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16464 entries, 0 to 16463
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Claim_ID                16464 non-null  object
 1   Policy_ID               16464 non-null  object
 2   Claim_Date              16464 non-null  object
 3   Claim_Amount            16464 non-null  int64
 4   Claim_Status            16464 non-null  object
 5   Claim_Type              16464 non-null  object
 6   Claim_Processing_Days   16464 non-null  int64
 7   Customer_ID_x           16464 non-null  object
 8   Policy_Type             16464 non-null  object
 9   Policy_Start_Date       16464 non-null  object
 10  Policy_End_Date         16464 non-null  object
 11  Policy_Status           16464 non-null  object
 12  Coverage_Amount         16464 non-null  float64
 13  Premium_Amount          16464 non-null  float64
 14  Payment_Frequency       16464 non-null  object
 15  Claim_To_Premium_Ratio  16464 non-null  float64
 16  Customer_Name           16464 non-null  object
 17  Age                     16464 non-null  float64
 18  Gender                  16464 non-null  object
 19  Marital_Status          16464 non-null  object
 20  Occupation              16464 non-null  object
 21  City                    16464 non-null  object
 22  Income                  16464 non-null  float64
 23  Age_Group               16464 non-null  object
 24  Transaction_ID          16464 non-null  object
 25  Customer_ID_y           16464 non-null  object
 26  Risk_Level              16464 non-null  object
 27  Previous_Claims         16464 non-null  float64
 28  Customer_Risk_Score     16464 non-null  float64
 29  Risk_Weight             16464 non-null  float64
dtypes: float64(8), int64(2), object(20)
memory usage: 3.8+ MB

In [ ]:
# Drop rows that contain any NaN/null values
data_base.dropna(how='any', inplace=True)
data_base.reset_index(drop=True, inplace=True)

# Model Creation(Linear Regression)

In [ ]:
from sklearn.preprocessing import LabelEncoder
lc=LabelEncoder()

data_base.Claim_Status = lc.fit_transform(data_base.Claim_Status)
data_base.Claim_Type = lc.fit_transform(data_base.Claim_Type)

In [ ]:
data_base.head()

,Claim_ID,Policy_ID,Claim_Date,Claim_Amount,Claim_Status,Claim_Type,Claim_Processing_Days,Customer_ID_x,Policy_Type,Policy_Start_Date,...,Occupation,City,Income,Age_Group,Transaction_ID,Customer_ID_y,Risk_Level,Previous_Claims,Customer_Risk_Score,Risk_Weight
0,CLM_000002,POL_000002,2025-09-24,424428,2,2,8,CUST_000002,Motor,2025-08-22,...,Self-Employed,Pune,2771559.0,18-25,TXN_000002,CUST_000002,High,4.0,91.94,3.0
1,CLM_000004,POL_000004,2023-08-12,2082174,0,0,40,CUST_000004,Home,2021-03-24,...,Salaried,Hyderabad,723630.0,18-25,TXN_000004,CUST_000004,Low,0.0,17.10,1.0
2,CLM_000005,POL_000005,2026-01-27,719296,0,4,6,CUST_000005,Motor,2024-10-27,...,Self-Employed,Pune,1891551.0,41-60,TXN_000005,CUST_000005,Low,1.0,29.90,1.0
3,CLM_000007,POL_000007,2023-08-23,93100,1,2,10,CUST_000007,Home,2022-10-31,...,Self-Employed,Bangalore,2437108.0,41-60,TXN_000007,CUST_000007,High,4.0,90.06,3.0
4,CLM_000012,POL_000012,2024-08-01,97597,0,0,34,CUST_000012,Travel,2022-12-10,...,Salaried,Chennai,388224.0,18-25,TXN_000012,CUST_000012,Medium,1.0,38.63,2.0

In [ ]:
#Model Creation

X=data_base[['Claim_Processing_Days',
        'Coverage_Amount',
        'Premium_Amount',
        'Claim_To_Premium_Ratio',
        'Age',
        'Income',
        'Customer_Risk_Score',
        ]]
y=data_base.Claim_Amount

In [ ]:
# Independent and Dependent variable creation
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size =0.2,random_state =4)

In [ ]:
X_train

,Claim_Processing_Days,Coverage_Amount,Premium_Amount,Claim_To_Premium_Ratio,Age,Income,Customer_Risk_Score
1971,19,3038345.0,152608.0,3.642915,54.0,1258795.0,47.11
4812,19,4390658.0,90859.0,8.656578,59.0,1842497.0,75.71
2431,7,1712746.0,70567.0,14.666856,43.0,2038626.0,35.49
10628,26,3139987.0,98334.0,13.556308,43.0,2497946.0,71.23
11764,4,3562592.0,120266.0,15.997780,58.0,391330.0,82.03
...,...,...,...,...,...,...,...
14445,26,2245001.0,94026.0,13.281273,22.0,2281720.0,86.75
8039,34,2813675.0,128988.0,11.585233,46.0,2729240.0,8.56
9274,24,3441068.0,65061.0,12.878883,65.0,444128.0,70.43
11863,18,261240.0,15621.0,7.764548,52.0,1484264.0,48.34
8366,5,4632702.0,68104.0,27.993069,51.0,2436656.0,53.61

In [ ]:
y_train

1971      555938
4812      786528
2431     1034996
10628    1333046
11764    1923989
          ...
14445    1248785
8039     1494356
9274      837913
11863     121290
8366     1906440
Name: Claim_Amount, Length: 13171, dtype: int64

In [ ]:
X_test

,Claim_Processing_Days,Coverage_Amount,Premium_Amount,Claim_To_Premium_Ratio,Age,Income,Customer_Risk_Score
9938,45,2525324.0,54207.0,15.587304,32.0,932686.0,25.46
10461,12,578317.0,9467.0,19.947819,18.0,1440072.0,52.22
8486,3,1199371.0,45018.0,17.634635,45.0,485239.0,27.92
4565,27,1635421.0,37698.0,6.228235,49.0,2621711.0,41.81
9903,5,4684930.0,155644.0,7.613464,44.0,1689326.0,60.46
...,...,...,...,...,...,...,...
6328,44,3073857.0,74340.0,20.298224,28.0,2900665.0,43.99
661,36,4799194.0,229165.0,7.712740,39.0,2445134.0,35.30
6160,10,2185098.0,62566.0,14.398267,53.0,596972.0,89.29
6637,38,1799856.0,71253.0,8.195823,24.0,1715953.0,89.17
10330,10,1043671.0,43949.0,11.589775,46.0,673285.0,79.52

In [ ]:
#Step 3 creation model
from sklearn.linear_model import LinearRegression
LR =LinearRegression()
LR.fit(X_train,y_train)
y_predit = LR.predict(X_test)

In [ ]:
y_test

9938      844941
10461     188846
8486      793876
4565      234792
9903     1184990
          ...
6328     1508970
661      1767490
6160      900842
6637      583977
10330     509359
Name: Claim_Amount, Length: 3293, dtype: int64

In [ ]:
y_predit

array([843162.38770635, 519790.39736488, 788030.53067677, ...,
       839523.41084268, 504919.6530174 , 432261.88882352])

In [ ]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
r2score=r2_score(y_test,y_predit)

In [ ]:
r2score

0.7884015540935845

In [ ]:
import math
print(mean_squared_error(y_test,y_predit))
print(math.sqrt(mean_squared_error(y_test,y_predit)))

120774688013.41486
347526.5285030984

In [ ]:
import pandas as pd

# Actual aur Predicted values ka ek naya DataFrame banana
comparison_df = pd.DataFrame({
    'Actual_Claim': y_test.values,
    'Predicted_Claim': y_predit
})

# Pehle 10 rows ko aamne-samne print karke dekhna
print(comparison_df.head(10))

   Actual_Claim  Predicted_Claim
0        844941     8.431624e+05
1        188846     5.197904e+05
2        793876     7.880305e+05
3        234792     1.526286e+05
4       1184990     1.460260e+06
5        524777     4.110565e+05
6        489496     5.489024e+05
7         66140    -2.539772e+05
8        809612     7.369469e+05
9        225302     3.109071e+05

Linnear regression is working good with this dataset after merging all the tables in 1 dataframe

#Random Forest Regressor

In [ ]:
#Expected Claim Amount

# Import libraries
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

In [ ]:
# Spliting the data
X=data_base[['Claim_Processing_Days',
        'Coverage_Amount',
        'Premium_Amount',
        'Claim_To_Premium_Ratio',
        'Age',
        'Income',
        'Customer_Risk_Score',
        ]]
y=data_base.Claim_Amount

In [ ]:
# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
# Create and train Random Forest Regressor model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predict and check metrics
y_pred = model.predict(X_test)
print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

R2 Score: 0.9986179410165805
MAE: 15168.013829334952

#XGBoost Regressor

In [ ]:
#importing libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
from xgboost import XGBRegressor

In [ ]:
pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.13/dist-packages (3.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost) (1.16.3)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.32.3)

In [ ]:
# Spliting the data
X=data_base[['Claim_Processing_Days',
        'Coverage_Amount',
        'Premium_Amount',
        'Claim_To_Premium_Ratio',
        'Age',
        'Income',
        'Customer_Risk_Score',
        ]]
y=data_base.Claim_Amount

In [ ]:
#4 Train Test Split
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [ ]:
#5. Model Creation
model = XGBRegressor (
    n_estimators=100,
    learning_rate = 0.1,
    max_depth = 4,
    eval_metric = 'rmse'
                     )

In [ ]:
#6 Model Training
model.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric='rmse', feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
#7 Prediction
y_pred = model.predict(X_test)

In [ ]:
#8.Evaluation
rmse = np.sqrt(mean_squared_error(y_test,y_pred))
r2 = r2_score(y_test,y_pred)

In [ ]:
print("RMSE:",rmse)
print("r2 score:",r2)

RMSE: 51194.35218849829
r2 score: 0.9954720735549927

#Risk Classification

Predict: Customer Risk Level

**Logistic Regression**

In [ ]:
data_base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16464 entries, 0 to 16463
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Claim_ID                16464 non-null  object
 1   Policy_ID               16464 non-null  object
 2   Claim_Date              16464 non-null  object
 3   Claim_Amount            16464 non-null  int64
 4   Claim_Status            16464 non-null  int64
 5   Claim_Type              16464 non-null  int64
 6   Claim_Processing_Days   16464 non-null  int64
 7   Customer_ID_x           16464 non-null  object
 8   Policy_Type             16464 non-null  object
 9   Policy_Start_Date       16464 non-null  object
 10  Policy_End_Date         16464 non-null  object
 11  Policy_Status           16464 non-null  object
 12  Coverage_Amount         16464 non-null  float64
 13  Premium_Amount          16464 non-null  float64
 14  Payment_Frequency       16464 non-null  object
 15  Claim_To_Premium_Ratio  16464 non-null  float64
 16  Customer_Name           16464 non-null  object
 17  Age                     16464 non-null  float64
 18  Gender                  16464 non-null  object
 19  Marital_Status          16464 non-null  object
 20  Occupation              16464 non-null  object
 21  City                    16464 non-null  object
 22  Income                  16464 non-null  float64
 23  Age_Group               16464 non-null  object
 24  Transaction_ID          16464 non-null  object
 25  Customer_ID_y           16464 non-null  object
 26  Risk_Level              16464 non-null  object
 27  Previous_Claims         16464 non-null  float64
 28  Customer_Risk_Score     16464 non-null  float64
 29  Risk_Weight             16464 non-null  float64
dtypes: float64(8), int64(4), object(18)
memory usage: 3.8+ MB

In [ ]:
print(data_base.columns)

Index(['Claim_ID', 'Policy_ID', 'Claim_Date', 'Claim_Amount', 'Claim_Status',
       'Claim_Type', 'Claim_Processing_Days', 'Customer_ID_x', 'Policy_Type',
       'Policy_Start_Date', 'Policy_End_Date', 'Policy_Status',
       'Coverage_Amount', 'Premium_Amount', 'Payment_Frequency',
       'Claim_To_Premium_Ratio', 'Customer_Name', 'Age', 'Gender',
       'Marital_Status', 'Occupation', 'City', 'Income', 'Age_Group',
       'Transaction_ID', 'Customer_ID_y', 'Risk_Level', 'Previous_Claims',
       'Customer_Risk_Score', 'Risk_Weight'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder
lc=LabelEncoder()

data_base.Risk_Level = lc.fit_transform(data_base.Risk_Level)
data_base.Occupation =lc.fit_transform(data_base.Occupation)

In [ ]:
# Model Creation
#Split the columns
X=data_base[['Income',
             'Age',
             'Previous_Claims',
             'Claim_To_Premium_Ratio',
             'Risk_Weight',
             'Customer_Risk_Score',
             'Coverage_Amount',
             'Premium_Amount',
             'Claim_Amount',
             'Occupation']]

y=data_base.Risk_Level

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size =0.2,random_state =4)

In [ ]:
X_test

,Income,Age,Previous_Claims,Claim_To_Premium_Ratio,Risk_Weight,Customer_Risk_Score,Coverage_Amount,Premium_Amount,Claim_Amount,Occupation
9938,932686.0,32.0,1.0,15.587304,1.0,25.46,2525324.0,54207.0,844941,1
10461,1440072.0,18.0,1.0,19.947819,2.0,52.22,578317.0,9467.0,188846,3
8486,485239.0,45.0,1.0,17.634635,1.0,27.92,1199371.0,45018.0,793876,2
4565,2621711.0,49.0,1.0,6.228235,2.0,41.81,1635421.0,37698.0,234792,1
9903,1689326.0,44.0,2.0,7.613464,3.0,60.46,4684930.0,155644.0,1184990,1
...,...,...,...,...,...,...,...,...,...,...
6328,2900665.0,28.0,1.0,20.298224,2.0,43.99,3073857.0,74340.0,1508970,1
661,2445134.0,39.0,1.0,7.712740,2.0,35.30,4799194.0,229165.0,1767490,0
6160,596972.0,53.0,4.0,14.398267,3.0,89.29,2185098.0,62566.0,900842,0
6637,1715953.0,24.0,4.0,8.195823,3.0,89.17,1799856.0,71253.0,583977,3
10330,673285.0,46.0,3.0,11.589775,3.0,79.52,1043671.0,43949.0,509359,0

In [ ]:
#creation model
from sklearn.linear_model import LogisticRegression
clf =LogisticRegression()
clf.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
X_train

,Income,Age,Previous_Claims,Claim_To_Premium_Ratio,Risk_Weight,Customer_Risk_Score,Coverage_Amount,Premium_Amount,Claim_Amount,Occupation
1971,1258795.0,54.0,1.0,3.642915,2.0,47.11,3038345.0,152608.0,555938,4
4812,1842497.0,59.0,3.0,8.656578,3.0,75.71,4390658.0,90859.0,786528,1
2431,2038626.0,43.0,1.0,14.666856,2.0,35.49,1712746.0,70567.0,1034996,0
10628,2497946.0,43.0,3.0,13.556308,3.0,71.23,3139987.0,98334.0,1333046,3
11764,391330.0,58.0,3.0,15.997780,3.0,82.03,3562592.0,120266.0,1923989,0
...,...,...,...,...,...,...,...,...,...,...
14445,2281720.0,22.0,3.0,13.281273,3.0,86.75,2245001.0,94026.0,1248785,0
8039,2729240.0,46.0,0.0,11.585233,1.0,8.56,2813675.0,128988.0,1494356,3
9274,444128.0,65.0,3.0,12.878883,3.0,70.43,3441068.0,65061.0,837913,0
11863,1484264.0,52.0,2.0,7.764548,2.0,48.34,261240.0,15621.0,121290,0
8366,2436656.0,51.0,2.0,27.993069,2.0,53.61,4632702.0,68104.0,1906440,1

In [ ]:
y_train

1971     2
4812     0
2431     2
10628    0
11764    0
        ..
14445    0
8039     1
9274     0
11863    2
8366     2
Name: Risk_Level, Length: 13171, dtype: int64

In [ ]:
y_pred = clf.predict(X_test)
y_pred

array([2, 0, 2, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score

In [ ]:
# Metrics calculate karein (average='weighted' use karein multiclass ke liye)
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, average="weighted"))
print("Precision Score:", precision_score(y_test, y_pred, average="weighted"))
print("Recall Score:", recall_score(y_test, y_pred, average="weighted"))

# 3. Confusion Matrix check karne ke liye
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy Score: 0.5608867294260552
F1 Score: 0.5445413950570169
Precision Score: 0.5457142701001325
Recall Score: 0.5608867294260552

Confusion Matrix:
[[ 496   17  400]
 [   5  130  477]
 [ 383  164 1221]]

#Random Forest Classifier

In [ ]:
#Import libraries
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [ ]:
# Model Creation
#Split the columns
X=data_base[['Income',
             'Age',
             'Previous_Claims',
             'Claim_To_Premium_Ratio',
             'Coverage_Amount',
             'Premium_Amount',
             'Claim_Amount',
             'Occupation']]

y=data_base.Risk_Level

In [ ]:
# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

In [ ]:
# Create and train Random Forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
# Predict and check accuracy
y_pred = model.predict(X_test)
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, average="weighted"))
print("Precision Score:", precision_score(y_test, y_pred, average="weighted"))
print("Recall Score:", recall_score(y_test, y_pred, average="weighted"))

Accuracy Score: 0.9198299423018524
F1 Score: 0.9194419977736139
Precision Score: 0.9218008231884282
Recall Score: 0.9198299423018524

this algorithm is showing 91% accurate customer risk level

#XGBoost Classifier

In [ ]:
#importing libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
from xgboost import XGBClassifier

In [ ]:
#Split the columns
X=data_base[['Income',
             'Age',
             'Previous_Claims',
             'Claim_To_Premium_Ratio',
             'Coverage_Amount',
             'Premium_Amount',
             'Claim_Amount',
             'Occupation']]

y=data_base.Risk_Level

In [ ]:
#4 Train Test Split
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [ ]:
# Create and train XGBoost classifier model
model = XGBClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
# Predict and check accuracy
# Predict and check accuracy
y_pred = model.predict(X_test)
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, average="weighted"))
print("Precision Score:", precision_score(y_test, y_pred, average="weighted"))
print("Recall Score:", recall_score(y_test, y_pred, average="weighted"))

Accuracy Score: 0.9149711509262071
F1 Score: 0.9146940526008995
Precision Score: 0.9164261331316945
Recall Score: 0.9149711509262071